export const project = [
  {
    img: "https://user-images.githubusercontent.com/98772205/235708646-26984d16-d87b-41aa-b6da-099dd3f27702.jpg",
    title: "Levo Clone(Extrnal Project)",
    desc: "Levo is an one of the leading platfrom which provides services in many tech category like Web Development Mobile Applications Custom Softwares UI/UX Graphic Design SEO Optimization Performance Marketing and Staff Augmentation",
    tech: "Nextjs tailwind Css",
    git: "https://github.com/mdshahbajalam7/team9-levolabz-clone",
    deploy: "https://team9-levolabz-clone.vercel.app/",
     },
    {
    img: "https://mms.businesswire.com/media/20161214005486/en/559884/5/AmazonPrimeVideo-com_HiRes.jpg",
    title: "Amazon Prime Video Clone",
    desc: "Amazon Prime Video, also known simply as Prime Video, is an American subscription video on-demand over-the-top streaming and rental service of Amazon offered as a standalone service or as part of Amazon's Prime subscription.",
    tech: "HTML CSS, JAVASCRIPT",
    git: "https://github.com/mdshahbajalam7/primeVideoProject",
    deploy: "https://nervous-sammet-6ff0d4.netlify.app/",
   },
  {
    img: "https://static.borngroup.com/uploads/2020/07/SS1-2-1280x0-c-default.jpg",
    title: "Tanishq-Clone",
    desc: "Tanishq has emerged as India's fastest growing jewellery brand and is a name which signifies superior craftsmanship, exclusive designs and superlative product quality.",
    tech: "HTML CSS, JAVASCRIPT, Tailwind",
    git: "https://github.com/mdshahbajalam7/tanishq",
    deploy: "https://melodic-youtiao-f6a1de.netlify.app/",
    },

  {
    img: "https://d1gzz21cah5pzn.cloudfront.net/img/websites/h/hin/hindustantimes.com-desktop@2x.1652906598.jpg",
    title: "Hindustantimes Clone",
    desc: "Hindustan Times is an Indian English-language daily newspaper the Indian independence nationalist daily Hindustan Times is an Indian English-language daily newspaper.",
    tech: "CSS, JAVASCRIPT, React, Redux, Styled-Component, Bootstrap,",
    git: "https://github.com/mdshahbajalam7/HindustanTimes_Clone",
    deploy: "https://github.com/mdshahbajalam7/HindustanTimes_Clone",
    },
  {
    img: "https://img.krishijagran.com/media/39688/kimaye.jpg",
    title: "Kimaye Clone",
    desc: "Kimaye. Brand. Growers of India's finest fruits, we want to make eating fruits a worry-free and delightful experience for you.",
    tech: "HTML, CSS, JAVASCRIPT, React js, redux, MongoDB, Node JS",
    git: "https://github.com/mdshahbajalam7/Kimaye",
    deploy: "https://mykimaye.netlify.app/",
  },
  {
    img: "https://user-images.githubusercontent.com/96000964/180591743-63917918-25ed-4043-9f82-7b7d2bda4dd6.png",
    title: "Bigbasket Clone",
    desc: "The best online grocery store in India. bigbasket is an online supermarket for all your daily needs.Big Basket is one of the largest online grocery super market in India. cities in India.",
    tech: "HTML, CSS, JAVASCRIPT, DOM, React Js, Redux, Node JS, MongooDB Atlas, Material Ui",
    git: "https://github.com/jeny008/quixotic-snail-9802",
    deploy: "https://bigbasket-clone-web16.netlify.app/",
     },
  // {
  //   img: "https://cdn4.xsplit.com/helpdesk/images/i/o/450745586/09b99fd174bb8803bf863b63/001.gif",
  //   title: "Google Meet Clone",
  //   desc: "This is a video conferencing and a chatting web application through which you can devlop a chatting application and video can do video chatting with individual or in a group as well.",
  //   tech: "HTML, CSS, JAVASCRIPT, DOM, React Js, Redux, Node JS, MongooDB Atlas, Material Ui",
  //   git: "https://github.com/mdshahbajalam7/Smooth-shark",
  //   deploy: "https://minichatingapp.netlify.app/",
  //    },

  // {
  //   img: "https://external-preview.redd.it/MWGKhoIU0m0zScLdtX582Un9EiEoAXnE099kORZDadA.png?format=pjpg&auto=webp&s=b90ec7e92e1807e3cbfb86f03138c63e23e3d717",
  //   title: "Spotify Clone",
  //   desc: "Master modern web development by building an improved version of Spotify. With a modern homepage, fully-fledged music player, search, lyrics, song exploration features, search, popular music.",
  //   tech: "redux, javascript, reactjs, rapidapi",
  //   git: "https://github.com/mdshahbajalam7/Music-App-",
  //   deploy: "https://musicappspotify.netlify.app/",
  //   },
//   jsdkfjaskjdf end
  // {
  //   img: "https://user-images.githubusercontent.com/62937819/84504960-71862780-acef-11ea-9c57-63d755eec333.png",
  //   title: "YouTube Clone",
  //   desc: "A web application Where you can watch movies, songs and any kind of videos. you can search videos. I created this app in unit 3 using advance javascript. data comming from API.",
  //   tech: "HTML, CSS, JAVASCRIPT, DOM, React Js, RapidApi, Material Ui",
  //   git: "https://github.com/mdshahbajalam7/YouTube",
  //   deploy: "https://myprojectyoutube.netlify.app/",
  //  },
  // {
  //   img: "https://miro.medium.com/max/1400/1*mzMIXN2JodV2taEBzmUKLg.png",
  //   title: "Curd Operation ",
  //   desc: "A web application where you can add Employee Curd Operation. I implemented,Post, add, delete,put, and pagination functionality using react, with moc-server.",
  //   tech: "React, Material Ui",
  //   git: "https://github.com/mdshahbajalam7/curdopperation",
  //   deploy: "https://curdoperationwithreact.netlify.app/",
  //  },
//   {
//     img: "https://pbs.twimg.com/media/FUPawD4XEAIZBaf?format=jpg&name=small",
//     title: "Resturent App -2",
//     desc: "A web application where you can Recipe, Today's Deal, Today's best Recipe. I implemented search functionality using advance javascript, with API.",
//     tech: "HTML, CSS, Javascript",
//     git: "https://github.com/iamdebobrota/Food-App-1",
//     deploy: "https://admiring-mayer-8d32d3.netlify.app",
//     // linkdin: " https://admiring-mayer-8d32d3.netlify.app",
//   },
//   {
//     img: "https://pbs.twimg.com/media/FUPdoyzWAAElc7d?format=png&name=small",
//     title: "Tic Tac Toe Game",
//     desc: "A web application where you can Play the game in online. I created this game using React. ",
//     tech: "React, CSS",
//     git: "https://github.com/iamdebobrota/Tic-Tac-Toe",
//     deploy: "https://imaginative-alpaca-d88bb1.netlify.app",
//     // linkdin:
//     //   "https://www.linkedin.com/posts/debobrota-haldar-3340651aa_masaischool-reactjs-activity-6920827752250040320-xgtp?utm_source=linkedin_share&utm_medium=member_desktop_web",
//   },
];
